---
title: "Project"
output: html_document
date: "2023-12-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```






















# Data Pre-processing

```{r,results='markup'}
data= read.csv('DataCoSupplyChainDataset.csv')
head(data)
```


```{r,results='markup'}
str(data)
```


```{r,results='markup'}
dim(is.na(data))
```


```{r,results='markup'}
data$`Customer.Full.Name` <- paste(data$`Customer.Fname`, data$`Customer.Lname`)
```
```{r,results='markup'}
colSums(is.na(data))
```

```{r,results='markup'}
data[1, ]

```

```{r,results='markup'}
data$Customer.Email <- NULL
data$Customer.Password <- NULL
data$Order.Zipcode <-NULL
data$Product.Description <- NULL
data$Product.Image<-NULL
data$order.date..DateOrders. <- NULL
data$shipping.date..DateOrders.<- NULL
data$Customer.Fname <- NULL
data$Customer.Lname <- NULL
data$Product.Status <-NULL
data$Customer.Street <- NULL
data$Latitude<- NULL
data$Longitude <- NULL
```

```{r,results='markup'}
data[1,]
```

```{r,results='markup'}
colSums(is.na(data))
```

```{r,results='markup'}
data <- na.omit(data)
```

```{r,results='markup'}
dim(data)
```

```{r,results='markup'}
str(data)
```

```{r,results='markup'}
unique_values_count <- sapply(data, function(x) length(unique(x)))
unique_values_count
```


```{r,results='markup'}
colnames(data)
```





```{r,results='markup'}
sapply(data, class)
```

```{r,results='markup'}
value_counts <- table(data$Late_delivery_risk)
value_counts
```



```{r,results='markup'}
data[1,]
```
```{r,results='markup'}
install.packages('corrplot')
```

```{r, results='markup'}
library(corrplot)

numeric_data <- data[, sapply(data, is.numeric)]
cor_matrix <- cor(numeric_data)
corrplot(cor_matrix, method = "color", type = "upper", order = "hclust", tl.col = "black", tl.srt = 45)
```


With this Correlation plot, we can observe that there are columns that are redundant like `Order.Item.Product.Price` and `Product.Price`. So let's remove the redundant colmns and plot the correlation again.

```{r, results='markup'}
# deleting redundant columns
data$Order.Item.Product.Price <- NULL
data$Sales.per.customer <- NULL
data$Order.Item.Total <- NULL
data$Order.Customer.Id <- NULL
data$Order.Item.Id <- NULL
data$Order.Profit.Per.Order <- NULL
```



# EDA

```{r, results='markup'}
# Correlation plot
numeric_data <- data[, sapply(data, is.numeric)]
cor_matrix <- cor(numeric_data)
corrplot(cor_matrix, method = "color", type = "upper", order = "hclust", tl.col = "black", tl.srt = 45)
```

```{r,results='markup'}
library(ggplot2)
library(dplyr)

custom_colors <- c("#004c6d", "#005b8f", "#0072b2", "#0088d2", "#009fdd")


par(mar = c(5, 5, 4, 2))


category_counts <- table(data$Type)
percentage <- round((category_counts / sum(category_counts)) * 100, 2)

# Create labels with percentages
labels_with_percentage <- paste(names(category_counts), "\n", format(percentage, nsmall = 2), "%", sep = "")


pie(category_counts,
    labels = labels_with_percentage,

    col = custom_colors,
    cex = 0.8,
    init.angle = 90, 
    border = "white" 
)


legend("topright",
       legend = names(category_counts),
       fill = custom_colors,
       cex = 0.8, 
       bty = "n"
)

title(main = "Distribution of Payment Methods", cex.main = 2)
```


```{r, results='markup'}
# Grouping by Market
market <- data %>% group_by(Market)

# Grouping by Order Region
region <- data %>% group_by(`Order.Region`)

# Plotting Total Sales for all Markets
plot_market <- market %>% summarise(total_sales = sum(`Sales`)) %>%
  arrange(desc(total_sales)) %>%
  ggplot(aes(x = reorder(Market, -total_sales), y = total_sales)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(title = "Total Sales for all Markets", x = "Market", y = "Total Sales") +
  theme_minimal()

# Plotting Total Sales for all Regions
plot_region <- region %>% summarise(total_sales = sum(`Sales`)) %>%
  arrange(desc(total_sales)) %>%
  ggplot(aes(x = reorder(`Order.Region`, -total_sales), y = total_sales)) +
  geom_bar(stat = "identity", fill = "lightgreen") +
  labs(title = "Total Sales for all Regions", x = "Order Region", y = "Total Sales") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

# Display the plots
print(plot_market)
print(plot_region)
```

```{r, results='markup'}
total_sales_per_category <- data %>%
  group_by(Category.Name) %>%
  summarize(Total.Sales = sum(Sales)) %>%
  arrange(desc(Total.Sales))


top_10_categories <- head(total_sales_per_category, 10)


ggplot(top_10_categories, aes(x = reorder(Category.Name, Total.Sales), y = Total.Sales / 1e6)) + 
  geom_bar(stat = "identity", fill = "steelblue") +
  coord_flip() + 
  labs(title = "Top Performers: Highest-Selling Product Categories",
       x = "Categories",
       y = "Total Sales (in Millions)") +
  theme_minimal() +
  theme(axis.text.y = element_text(angle = 0, hjust = 1)) + 
  scale_y_continuous(breaks = c(0, 2, 4, 6), labels = c("0", "2", "4", "6")) 
```

#Model Building

```{r,results='markup'}
train_data <- data
```


```{r,results='markup'}
unique_values <- unique(train_data$Order.Status)
unique_values

```


```{r,results='markup'}
train_data$fraud <- ifelse(train_data$`Order.Status` == 'SUSPECTED_FRAUD', 1, 0)
train_data$late_delivery <- ifelse(train_data$`Delivery.Status` == 'Late delivery', 1, 0)
head(train_data,2)
```



```{r,results='markup'}
library(dplyr)
train_data <- train_data %>%
  select(-Delivery.Status, -Late_delivery_risk, -Order.Status)
head(train_data)
```
```{r,results='markup'}
str(train_data)
```




```{r,results='markup'}
library(forcats)

train_data <- train_data %>%
  mutate(
    `Customer.Country` = as.integer(fct_recode(as_factor(`Customer.Country`), .default = "NA")),
    Market = as.integer(fct_recode(as_factor(Market), .default = "NA")),
    Type = as.integer(fct_recode(as_factor(Type), .default = "NA")),
    `Product.Name` = as.integer(fct_recode(as_factor(`Product.Name`), .default = "NA")),
    `Customer.Segment` = as.integer(fct_recode(as_factor(`Customer.Segment`), .default = "NA")),
    `Customer.State` = as.integer(fct_recode(as_factor(`Customer.State`), .default = "NA")),
    `Order.Region` = as.integer(fct_recode(as_factor(`Order.Region`), .default = "NA")),
    `Order.City` = as.integer(fct_recode(as_factor(`Order.City`), .default = "NA")),
    `Category.Name` = as.integer(fct_recode(as_factor(`Category.Name`), .default = "NA")),
    `Customer.City` = as.integer(fct_recode(as_factor(`Customer.City`), .default = "NA")),
    `Department.Name` = as.integer(fct_recode(as_factor(`Department.Name`), .default = "NA")),
    `Order.State` = as.integer(fct_recode(as_factor(`Order.State`), .default = "NA")),
    `Shipping.Mode` = as.integer(fct_recode(as_factor(`Shipping.Mode`), .default = "NA")),
    `Order.Country` = as.integer(fct_recode(as_factor(`Order.Country`), .default = "NA")),
    `Customer.Full.Name` = as.integer(fct_recode(as_factor(`Customer.Full.Name`), .default = "NA"))
  )
```

```{r,results='markup'}
library(caret)
set.seed(42)
xf <- train_data[, !(names(train_data) == "fraud")]
yf <- train_data$fraud
set_split_fraud <- createDataPartition(yf, p = 0.8, list = FALSE)
xf_train_fraud <- xf[set_split_fraud, ]
xf_test_fraud <- xf[-set_split_fraud, ]
yf_train <- yf[set_split_fraud]
yf_test <- yf[-set_split_fraud]
xl <- train_data[, !(names(train_data) == "late_delivery")]
yl <- train_data$late_delivery
set_split_late_delivery <- createDataPartition(yl, p = 0.8, list = FALSE)
xl_train_late_delivery <- xl[set_split_late_delivery, ]
xl_test_late_delivery <- xl[-set_split_late_delivery, ]
yl_train <- yl[set_split_late_delivery]
yl_test <- yl[-set_split_late_delivery]
```




```{r,results='markup'}
xf_train <- scale(xf_train_fraud)
xf_test <- scale(xf_test_fraud)
xl_train <- scale(xl_train_late_delivery)
xl_test <- scale(xl_test_late_delivery)
```

```{r,results='markup'}
classifier_model <- function(model_f, model_l, xf_train, xf_test, yf_train, yf_test, xl_train, xl_test, yl_train, yl_test) {
  model_f <- train(model_f, xf_train, yf_train)
  
  model_l <- train(model_l, xl_train, yl_train)
  
  yf_pred <- predict(model_f, xf_test)
  
  yl_pred <- predict(model_l, xl_test)
  
  accuracy_f <- sum(yf_pred == yf_test) / length(yf_test) * 100
  
  accuracy_l <- sum(yl_pred == yl_test) / length(yl_test) * 100
  
  recall_f <- sum(yf_pred == 1 & yf_test == 1) / sum(yf_test == 1) * 100
  
  recall_l <- sum(yl_pred == 1 & yl_test == 1) / sum(yl_test == 1) * 100
  
  f1_f <- 2 * (recall_f * accuracy_f) / (recall_f + accuracy_f)
  
  f1_l <- 2 * (recall_l * accuracy_l) / (recall_l + accuracy_l)
  
  cat("Accuracy of fraud status is:", accuracy_f, "%\n")
  cat("Recall score of fraud status is:", recall_f, "%\n")
  cat("F1 score of fraud status is:", f1_f, "%\n")
  cat("Accuracy of late delivery status is:", accuracy_l, "%\n")
  cat("Recall score of late delivery status is:", recall_l, "%\n")
  cat("F1 score of late delivery status is:", f1_l, "%\n")
}

```

#Model 1: Logistic Regression
```{r,results='markup'}
library(caret)

model_f <- glm(fraud ~ ., data = data.frame(fraud = yf_train, xf_train), family = binomial(link = "logit"))
model_l <- glm(late_delivery ~ ., data = data.frame(late_delivery = yl_train, xl_train), family = binomial(link = "logit"))
classifier_model <- function(model_f, model_l, xf_test, yf_test, xl_test, yl_test) {
  yf_pred <- predict(model_f, newdata = data.frame(xf_test), type = "response")
  
  yl_pred <- predict(model_l, newdata = data.frame(xl_test), type = "response")
  
  accuracy_f <- sum((yf_pred >= 0.5) == yf_test) / length(yf_test) * 100
  
  accuracy_l <- sum((yl_pred >= 0.5) == yl_test) / length(yl_test) * 100
  
  recall_f <- sum((yf_pred >= 0.5) & yf_test == 1) / sum(yf_test == 1) * 100
  
  recall_l <- sum((yl_pred >= 0.5) & yl_test == 1) / sum(yl_test == 1) * 100
  
  f1_f <- 2 * (recall_f * accuracy_f) / (recall_f + accuracy_f)
  
  f1_l <- 2 * (recall_l * accuracy_l) / (recall_l + accuracy_l)
  
  cat("Accuracy of fraud status is:", accuracy_f, "%\n")
  cat("Recall score of fraud status is:", recall_f, "%\n")
  cat("F1 score of fraud status is:", f1_f, "%\n")
  cat("Accuracy of late delivery status is:", accuracy_l, "%\n")
  cat("Recall score of late delivery status is:", recall_l, "%\n")
  cat("F1 score of late delivery status is:", f1_l, "%\n")
}
classifier_model(model_f, model_l, xf_test, yf_test, xl_test, yl_test)

```

#Model 2 Naive Bayes


```{r,results='markup'}

library(e1071)

model_f <- naiveBayes(yf_train ~ ., data = data.frame(yf_train, xf_train), laplace = 1)
model_l <- naiveBayes(yl_train ~ ., data = data.frame(yl_train, xl_train), laplace = 1)

classifier_model <- function(model_f, model_l, xf_test, yf_test, xl_test, yl_test) {
  yf_pred <- predict(model_f, newdata = data.frame(xf_test))
  
  yl_pred <- predict(model_l, newdata = data.frame(xl_test))
  
  accuracy_f <- sum(yf_pred == yf_test) / length(yf_test) * 100
  
  accuracy_l <- sum(yl_pred == yl_test) / length(yl_test) * 100
  
  recall_f <- sum(yf_pred == 1 & yf_test == 1) / sum(yf_test == 1) * 100
  
  recall_l <- sum(yl_pred == 1 & yl_test == 1) / sum(yl_test == 1) * 100
  
  f1_f <- 2 * (recall_f * accuracy_f) / (recall_f + accuracy_f)
  
  f1_l <- 2 * (recall_l * accuracy_l) / (recall_l + accuracy_l)
  
  cat("Accuracy of fraud status is:", accuracy_f, "%\n")
  cat("Recall score of fraud status is:", recall_f, "%\n")
  cat("F1 score of fraud status is:", f1_f, "%\n")
  cat("Accuracy of late delivery status is:", accuracy_l, "%\n")
  cat("Recall score of late delivery status is:", recall_l, "%\n")
  cat("F1 score of late delivery status is:", f1_l, "%\n")
}


classifier_model(model_f, model_l, xf_test, yf_test, xl_test, yl_test)


```

#Model 3 KNN

```{r, results='markup'}
if (!require(class)) {
  install.packages("class")
}
library(class)

model_f <- knn(xf_train, xf_test, yf_train, k = 1)
model_l <- knn(xl_train, xl_test, yl_train, k = 1)

classifier_model <- function(model_f, model_l, xf_test, yf_test, xl_test, yl_test) {
  accuracy_f <- sum(model_f == yf_test) / length(yf_test) * 100
  
  accuracy_l <- sum(model_l == yl_test) / length(yl_test) * 100
  
  recall_f <- sum(model_f == 1 & yf_test == 1) / sum(yf_test == 1) * 100
  
  recall_l <- sum(model_l == 1 & yl_test == 1) / sum(yl_test == 1) * 100
  
  f1_f <- 2 * (recall_f * accuracy_f) / (recall_f + accuracy_f)
  
  f1_l <- 2 * (recall_l * accuracy_l) / (recall_l + accuracy_l)
  
  cat("Accuracy of fraud status is:", accuracy_f, "%\n")
  cat("Recall score of fraud status is:", recall_f, "%\n")
  cat("F1 score of fraud status is:", f1_f, "%\n")
  cat("Accuracy of late delivery status is:", accuracy_l, "%\n")
  cat("Recall score of late delivery status is:", recall_l, "%\n")
  cat("F1 score of late delivery status is:", f1_l, "%\n")
}


classifier_model(model_f, model_l, xf_test, yf_test, xl_test, yl_test)
```

#Model 4 Random Forest

```{r,results='markup'}
if (!require(randomForest)) {
  install.packages("randomForest")
}
library(randomForest)
model_f <- randomForest(yf_train ~ ., data = data.frame(yf_train, xf_train), ntree = 100)
model_l <- randomForest(yl_train ~ ., data = data.frame(yl_train, xl_train), ntree = 100, mtry = 10)

classifier_model(model_f, model_l, xf_test, yf_test, xl_test, yl_test)
```
